sudo: false
dist: trusty
language: node_js
node_js:
  - 10.15.0
services:
  - mongodb
env:
  global
    - LOG_LEVEL=debug
    - PORT=8050
    - HOSTNAME=localhost
    - API_PREFIX=/api/v1
    - COMMENTS_DB_URL_TEST=mongodb://localhost:27017/comments_test
    - POSTS_DB_URL_TEST=mongodb://localhost:27017/posts_test
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn install
  - sleep 15 # inject an artificial wait before making the first connection
script:
  - yarn lint
  - yarn test
